version: '3.4'

services:
  mongo:
    image: mongo:4.4.1
    ports:
      - 27017:27017

  response-service:
    build: .
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo
    ports:
      - 3000:3000
